// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVrCbjPHKoIzmyCmajKpNYGhuwml_63Us',
    appId: '1:993033447341:web:1c66bfed94083d3fe6a324',
    messagingSenderId: '993033447341',
    projectId: 'xmca14',
    authDomain: 'xmca14.firebaseapp.com',
    storageBucket: 'xmca14.firebasestorage.app',
    measurementId: 'G-HCXM1C3C02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWty96mrKPCLSxvxvbHLgA_p6rVT9GLls',
    appId: '1:993033447341:android:6c6bdd32a76f5235e6a324',
    messagingSenderId: '993033447341',
    projectId: 'xmca14',
    storageBucket: 'xmca14.firebasestorage.app',
  );
}
